### ISSUE TITLE
繁体转简体好像有问题

### ISSUE THREAD

**Issue by pretenderlu** [yihong0618/epubhv#5]
PS C:\Users\LuQQ\Downloads\Telegram Desktop> epubhv d.epub --h --convert t2s
d.epub is to_horizontal
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\epubhv.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\epubhv\cli.py", line 85, in main
    e.run(method)
  File "C:\Python311\Lib\site-packages\epubhv\epubhv.py", line 288, in run
    self.change_epub_to_horizontal()
  File "C:\Python311\Lib\site-packages\epubhv\epubhv.py", line 205, in change_epub_to_horizontal
    soup = load_opf_meta_data(self.opf_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\epubhv\epubhv.py", line 51, in load_opf_meta_data
    content = f.read()
              ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x89 in position 267: illegal multibyte sequence

**Comment by yihong0618** [comment]
繁体转简体对吧

**Comment by pretenderlu** [comment]
是的

**Comment by yihong0618** [comment]
@pretenderlu 尝试修复了

pip install -U epubhv

**Comment by yihong0618** [comment]
@pretenderlu 关了哈有问题随时再打开

**Comment by yihong0618** [comment]
能提供下要翻译的书么？放在 issue 里应该能放下。

**Comment by pretenderlu** [comment]
嗯，我随便在好读上下了一本，试了下就不行。后缀改一下哈~
[d.zip](https://github.com/yihong0618/epubhv/files/12606962/d.zip)

**Comment by yihong0618** [comment]
OK

**Comment by yihong0618** [comment]
@pretenderlu 
我这里完全没问题。。。
pip install -U epubhv 这个命令你跑了么？

**Comment by pretenderlu** [comment]
啊，跑了呀，我再试一下

**Comment by yihong0618** [comment]
可能是 windows 的问题，我想想怎么解决

**Comment by pretenderlu** [comment]
你用的不是win？

**Comment by yihong0618** [comment]
mac, 我加个 errors ignore 再发个版本
稍等。

**Comment by yihong0618** [comment]
@pretenderlu 更新了
pip install -U epubhv  

之后再跑一遍试试？

**Comment by pretenderlu** [comment]
成功啦，太酷了！

**Comment by yihong0618** [comment]
OK
